### ISSUE TITLE
Add a way to collect feedback 

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/simplify-privacy-statements-V2#141]
This is to prepare for releasing more widely: https://trello.com/c/beA8Z11P/91-update-the-feedback-on-the-generator-to-reflect-the-cds-feedback-component

We can use the feedback component here: https://github.com/cds-snc/feedback-plugin

Documentation for implementing it is here: https://github.com/cds-snc/feedback-plugin/blob/master/Guidance%20for%20collecting%20feedback.pdf

**Comment by wmoussa-cds** [comment]
Not currently a product we will be investing to expand.
