### ISSUE TITLE
Terraform: create `app` module

### ISSUE THREAD

**Issue by patheard** [cds-snc/simplify-privacy-statements-V2#213]
## Description
Create a `/terragrunt/aws/app` Terraform module and the `/terragrunt/env/production/app` config that creates the Lambda function and Lambda function URL.

## Todo
- [x] [Lambda function](https://github.com/cds-snc/scan-files/blob/ece4d21257be07ced3cb84e3d13c5ff28e675e49/terragrunt/aws/api/lambda.tf#L1-L35): it can exist outside of a VPC
- [x] [Lambda function URL example](https://github.com/cds-snc/scan-files/blob/ece4d21257be07ced3cb84e3d13c5ff28e675e49/terragrunt/aws/api/lambda.tf#L93-L97).

## Related
- #207

**Comment by patheard** [comment]
This is blocked by #214.

**Comment by omartehsin1** [comment]
Complete and merged

**Comment by omartehsin1** [comment]
Currently debugging why Lambda server keeps timing out and giving us a 502 error. Likely has to do with the security groups (ingress, egress) not having the right configurations to access EFS. 

Will need to adjust ingress and add in an egress rule.

**Comment by omartehsin1** [comment]
Fixed issue, needed to add an egress rule for lambda to be able to access the EFS using port 2049

Also updated EFS security group to to EFS security group IDs from Lambda security group IDs
