### ISSUE TITLE
Terraform: create `hosted_zone` module

### ISSUE THREAD

**Issue by patheard** [cds-snc/simplify-privacy-statements-V2#256]
## Summary
Create a `hosted_zone` module that holds the Route 53 hosted zone for the project.  Here's [an example you can use](https://github.com/cds-snc/github-secret-scanning/tree/main/terragrunt/aws/hosted_zone).

- [x] Add the module.  As part of this, you'll define a [global `domain` input](https://github.com/cds-snc/github-secret-scanning/blob/main/terragrunt/env/common/common_variables.tf#L11-L14) that holds the URL for the new site.
- [x] Once the Route 53 hosted zone has been created, make a PR to the DNS repo that [adds subdomain delegation](https://github.com/cds-snc/dns/blob/bd00ed90aba78a8290068ff906403facd18bdd18/terraform/url-shortener.alpha.canada.ca.tf) to our hosted zone.  You can get the Nameserver records from the AWS console by viewing the hosted zone.  This PR can also remove the [2 unused CNAME records](https://github.com/cds-snc/dns/blob/bd00ed90aba78a8290068ff906403facd18bdd18/terraform/privacy-statements.alpha.canada.ca.tf) for the app.

The domain to use for this will be:
```
simplify-privacy-statements.alpha.canada.ca
```

**Comment by omartehsin1** [comment]
Module added [PR](https://github.com/cds-snc/simplify-privacy-statements-V2/pull/257)
