### ISSUE TITLE
Reproduce the share/save input feature from old app

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/simplify-privacy-statements-V2#39]
Here is an example: https://simplify-privacy-statements.herokuapp.com/generatedForm?id=recnP7Ve3u8KilQb9

Up for discussion: should we implement this the same way as before?

**Comment by sastels** [comment]
probably just copying the old way is the easiest for now? say we had a "save" button somewhere, and on the server it did all that airtable stuff and returned a page showing the link to  copy/paste?

**Comment by keithiopia** [comment]
One of the issues with the old save/share functionality was that it wasn't clear what 'Share' did. 
It's worth thinking about the behaviour when clicking on that button in terms of what it presents the user with (adding the string in the address bar was too subtle).
