### ISSUE TITLE
Use Dave's fancy new interface shortcuts

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#46]
merged into starter app here https://github.com/cds-snc/node-starter-app/pull/57

**Comment by smcmurtry** [comment]
Want to pull in all their changes? We could also use their more general solution to keeping the query params in the url after navigation.

**Comment by sastels** [comment]
yeah, in #48 I just pulled the lastest master of `node-starter-app` in.
