### ISSUE TITLE
Check logic conflicts

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#50]
As per Stevie-Ray's observation on Slack about video recording, is it possible to disable some options based on previous answers?
For example, if the researcher has selected 'anonymized' or 'anonymous', it shouldn't be possible to select a video recording option (they can't be anon).

Similarly, in the AirTable version, the clause "CDS will share publicly personal_information_disclosed_to_public." was appearing when the researcher picks 'public' or 'not confidential'. It should only appear when the researcher picks 'public'.

**Comment by sastels** [comment]
one idea: add validation schema to prevent submission. Add error under the 'recording' question to tell people not to choose 'video'. Add error under 'proof of consent' when choosing compensation:yes to tell people to choose written/paper option.

**Comment by sastels** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check logic conflicts](https://trello.com/c/7xucdjTM/67-check-logic-conflicts)

**Comment by keithiopia** [comment]
Added `"warning.anon"` and `"warning.consent"` in /locales/en.json. Hopefully it's clear which goes where :)
