### ISSUE TITLE
Add more to landing page

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#60]
explain exact point of the app, and that the researcher has to talk to their ATIP office.

**Comment by cmaczo** [comment]
https://trello.com/c/exWFdgKF/63-integrate-form-use-guidance-information-into-transaction

**Comment by keithiopia** [comment]
First run in [https://github.com/cds-snc/simplify-privacy-statements-V2/pull/53].
Next job is to format the start page.

**Comment by keithiopia** [comment]
https://github.com/cds-snc/simplify-privacy-statements-V2/pull/77
