### ISSUE TITLE
incorporate feedback from usability tests

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#63]

**Comment by adriannelee** [comment]
Focusing on the bugs 🐛
- [ ] Provide instructions to not capitalize the input (or, automatically change to lowercase)
- [ ] Remove spaces before periods
- [ ] Remove spaces before and after parentheses
- [ ] Remove duplicate periods
- [ ] “Your information will be form.confidential. This means your responses will not be linked to you.”
- [ ] Apply italics "The collection and use of your personal information by ESDC is authorized by the _ Department of Employment Social Development Act _ ."

**Comment by cmaczo** [comment]
Related to: https://trello.com/c/vQbIEY0I/52-test-rewritten-form-with-design-researchers
