### ISSUE TITLE
Add French / English agreement button

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#64]
Add a button beside the "Download Word Document" button for "French Translation" or "English Translation". This button can just switch language as the button in the upper right corner does.

**Comment by keithiopia** [comment]
Is this necessary? We could stack the French agreement under the English agreement, given how researchers are required to create both.

**Comment by keithiopia** [comment]
The need to add a 'Switch to French/English' button was confirmed in the Oct 10, 2019 research session.

**Comment by sastels** [comment]
Should probably move around buttons a bit, and make the "email a link" more prominent.
