### ISSUE TITLE
Translate form boilerplate into French

### ISSUE THREAD

**Issue by cmaczo** [cds-snc/simplify-privacy-statements-V2#66]
Translations go here: https://github.com/cds-snc/simplify-privacy-statements-V2/blob/master/routes/agreement-1/agreement-1-fr.njk

**Comment by keithiopia** [comment]
Bundle this is with translating everything: https://trello.com/c/HEMQqA3U/70-translate-new-question-fields-and-content-into-french

**Comment by keithiopia** [comment]
Sent for translation on Friday 18th
