### ISSUE TITLE
Disable additional questionairres for now

### ISSUE THREAD

**Issue by cmaczo** [cds-snc/simplify-privacy-statements-V2#67]
@sastels @smcmurtry Can we disable the additional questionnaires feature for now? And just provide one? I'd like to get this thing out the door with one.

**Comment by cmaczo** [comment]
https://trello.com/c/qAHZku6q/69-disable-additional-questionairres-for-now

**Comment by sastels** [comment]
we could just comment out the lines from the landing page and route config, essentially leaving everything in place code-wise for when we want to add a second.
