### ISSUE TITLE
Swap out 'cancel' for 'skip'

### ISSUE THREAD

**Issue by keithiopia** [cds-snc/simplify-privacy-statements-V2#80]
Replace the 'Skip' button at the bottom of the translations-1 route page with the 'Link to Filled Form' option. Rename it to 'Save your answers for later'.
Remove the 'Link to Filled Form' link from the agreements route pages.

**Comment by keithiopia** [comment]
https://trello.com/c/sPCxMWt7/72-replace-skip-with-save-on-translation-page

**Comment by sastels** [comment]
The only thing is that if we move the button there then the link will not contain the inputs that the user might type in on that translation page. Unless we do something like send them to another page, and **that page** will have the link on it.

**Comment by keithiopia** [comment]
As @smcmurtry says, just get rid of cancel.
Save can stay where it is for now, with the updated content around it, and changed to an email option.
