### ISSUE TITLE
make some fields mandatory in production

### ISSUE THREAD

**Issue by sastels** [cds-snc/simplify-privacy-statements-V2#81]
@keithiopia do you have a list?

**Comment by keithiopia** [comment]
> @keithiopia do you have a list?

The fields that everyone will have to fill out (which require translation) are:
`research_goal`
`session_activity`
`session_duration`
`personal_information_collected`

There will be other fields that require translation, but they're based on conditional questions, such as if the researcher is recording the participant etc.
