### ISSUE TITLE
Remove agreement page instructions from word doc

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/simplify-privacy-statements-V2#95]

**Comment by keithiopia** [comment]
Would it help if the part to be downloaded was in its own div? 
To complicate this job a bit, I've added wordmark instructions to `greement-1-en.njk`... sorry!

**Comment by smcmurtry** [comment]
> Would it help if the part to be downloaded was in its own div?
> To complicate this job a bit, I've added wordmark instructions to `greement-1-en.njk`... sorry!

Yes that is one way to do it, although nesting things in divs can make things less accessible. We could also search for some text in the html that represents the start of the document.
